# Generated by Django 4.0.4 on 2022-05-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
